# This file contains an example EU868 configuration.
# Importante: el "topic_prefix" debe coincidir con el prefijo usado por el Gateway Bridge.

[[regions]]
id = "eu868"
description = "EU868"
common_name = "EU868"

  [regions.gateway]
  topic_prefix = "eu868"

  [regions.network]
  mac_version = "LORAWAN_1_0_3"
  reg_params_revision = "A"

  adr_disabled = false

  min_dr = 0
  max_dr = 7

  [regions.network.rejoin_request]
  enabled = true

  [regions.network.class_b]
  ping_slot_dr = 3
  ping_slot_frequency = 869525000

  [regions.network.class_c]
  rx2_frequency = 869525000
  rx2_dr = 0

  [regions.network.chan_plan]
  [[regions.network.chan_plan.channels]]
  frequency = 868100000
  min_dr = 0
  max_dr = 5

  [[regions.network.chan_plan.channels]]
  frequency = 868300000
  min_dr = 0
  max_dr = 5

  [[regions.network.chan_plan.channels]]
  frequency = 868500000
  min_dr = 0
  max_dr = 5

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 12
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 11
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 10
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 9
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 8
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 7
  bandwidth = 125000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "LORA"
  spreading_factor = 7
  bandwidth = 250000
  bitrate = 0

  [[regions.network.chan_plan.data_rates]]
  modulation = "FSK"
  spreading_factor = 0
  bandwidth = 0
  bitrate = 50000