global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "gateway-bridge-us915_0"
    static_configs:
      - targets: ["chirpstack-gateway-bridge-us915-0:9100"]

  - job_name: "gateway-bridge-eu868"
    static_configs:
      - targets: ["chirpstack-gateway-bridge-eu868:9100"]

  - job_name: "gateway-bridge-au915_0"
    static_configs:
      - targets: ["chirpstack-gateway-bridge-au915-0:9100"]

  - job_name: "gateway-bridge-as923_4"
    static_configs:
      - targets: ["chirpstack-gateway-bridge-as923-4:9100"]