---
- hosts: all
  become: true

  vars:
    app_dir: /opt/pruebatcp1

  tasks:
    - name: Asegurar directorio de aplicaci√≥n
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Asegurar directorio mosquitto
      file:
        path: "{{ app_dir }}/mosquitto"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copiar mosquitto.conf
      copy:
        src: mosquitto/mosquitto.conf
        dest: "{{ app_dir }}/mosquitto/mosquitto.conf"
        owner: root
        group: root
        mode: "0644"

    - name: Copiar docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "0644"

    - name: Copiar Caddyfile
      copy:
        src: files/Caddyfile
        dest: "{{ app_dir }}/Caddyfile"
        owner: root
        group: root
        mode: "0644"

    - name: Pull y up (docker compose)
      command: docker compose up -d --pull always --remove-orphans
      args:
        chdir: "{{ app_dir }}"

    - name: Mostrar estado de contenedores
      command: docker compose ps
      args:
        chdir: "{{ app_dir }}"
      register: compose_ps

    - name: Debug estado docker compose
      debug:
        var: compose_ps.stdout