name: Go Build & Docker Push

on:
  push:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # ---------- BUILD CLIENT ----------
      - name: Build modbus client
        working-directory: client
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o modbus-client

      # ---------- BUILD SERVER ----------
      - name: Build modbus server
        working-directory: server
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o modbus-server

      # ---------- DOCKER LOGIN ----------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- BUILD & PUSH CLIENT IMAGE ----------
      - name: Build & push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile.client
          push: true
          tags: galvarez0/pruebatcp1:modbus-client

      # ---------- BUILD & PUSH SERVER IMAGE ----------
      - name: Build & push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile.server
          push: true
          tags: galvarez0/pruebatcp1:modbus-server